# Generated by Django 3.0.3 on 2020-07-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0002_auto_20200717_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
