# Generated by Django 3.0.3 on 2020-07-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0003_record_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Birthday',
            new_name='DOB',
        ),
        migrations.AlterField(
            model_name='record',
            name='Profile',
            field=models.ImageField(upload_to=''),
        ),
    ]
