# Generated by Django 2.2.7 on 2020-07-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0006_auto_20200719_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='Dob',
            field=models.DateField(),
        ),
    ]
