# Generated by Django 3.0.3 on 2020-07-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0007_auto_20200720_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AddField(
            model_name='record',
            name='ID',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Profile',
            field=models.ImageField(blank=True, help_text='Upload Image', upload_to=''),
        ),
    ]
