# Generated by Django 3.0.3 on 2020-07-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0008_auto_20200722_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='ID',
            new_name='Uid',
        ),
    ]
