# Generated by Django 3.0.3 on 2020-07-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0009_auto_20200722_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Profile',
            field=models.ImageField(blank=True, help_text='Upload Image', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
